use crate::*;

#[repr(C)]
pub struct Entity {
    pub xpos: int32,
    pub ypos: int32,
    pub xvel: int32,
    pub yvel: int32,
    pub speed: int32,
    pub values: [int32; 48],
    pub state: int32,
    pub angle: int32,
    pub scale: int32,
    pub rotation: int32,
    pub alpha: int32,
    pub animationTimer: int32,
    pub animationSpeed: int32,
    pub lookPosX: int32,
    pub lookPosY: int32,
    pub groupID: uint16,
    pub type_: uint8,
    pub propertyValue: uint8,
    pub priority: uint8,
    pub drawOrder: uint8,
    pub direction: uint8,
    pub inkEffect: uint8,
    pub animation: uint8,
    pub prevAnimation: uint8,
    pub frame: uint8,
    pub collisionMode: uint8,
    pub collisionPlane: uint8,
    pub controlMode: int8,
    pub controlLock: uint8,
    pub pushing: uint8,
    pub visible: uint8,
    pub tileCollisions: uint8,
    pub objectInteractions: uint8,
    pub gravity: uint8,
    pub left: uint8,
    pub right: uint8,
    pub up: uint8,
    pub down: uint8,
    pub jumpPress: uint8,
    pub jumpHold: uint8,
    pub scrollTracking: uint8,
    pub floorSensors: [uint8; 5],
}
